#!/bin/sh
(sleep 10 ; jack_connect tableSet:output1 system:playback_1) &
(sleep 10 ; jack_connect tableSet:output1 system:playback_2) &
java -cp .:..:crimson.jar -Dorg.xml.sax.driver=org.apache.crimson.parser.XMLReaderImpl  EventTableEditor.CSoundTableDriver $* | perl csound-filter.pl  | csound -dm6  -+rtaudio=jack -+jack_client=tableSet  -o devaudio -b 800 -B 2048 -L stdin  pv.orc pv.sco
