#!/bin/sh
(sleep 10 ; jack_connect pv:output1 system:playback_1) &
(sleep 10 ; jack_connect pv:output1 system:playback_2) &
DFL=pv.xml
export DFL
java -cp .:..:crimson.jar -Dorg.xml.sax.driver=org.apache.crimson.parser.XMLReaderImpl  EventTableEditor.CSoundTableDriver ${1-$DFL} | perl csound-filter.pl  | csound -dm6  -+rtaudio=jack -+jack_client=pv  -o devaudio -b 800 -B 2048 -L stdin  pv.orc pv.sco
