#!/bin/sh
perl generate.pl eventtemp ./Intkit*.wav
echo "java -Dorg.xml.sax.driver=org.apache.crimson.parser.XMLReaderImpl CSoundTableDriver ./INTKIT.xml | csound --sched -dm6 -L stdin -o devaudio eventtemp.orc eventtemp.sco"
java -cp .:crimson.jar -Dorg.xml.sax.driver=org.apache.crimson.parser.XMLReaderImpl EventTableEditor.CSoundTableDriver ./INTKIT.xml | csound  -dm6 -L stdin -o devaudio eventtemp.orc eventtemp.sco

